version: '3.9'
services:
  api:
    image: apellun/flask-app:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    ports:
      - 80:80
    volumes:
      - /Users/apellun/PycharmProjects/flask_api_term_project/coursework_3_source/volumes:/code/volumes
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=production