version: '3.9'
services:
  api:
    image: apellun/flask-app:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    ports:
      - 80:80
    volumes:
      - ./volumes:/code/volumes
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=production
volumes:
  volumes: